### ISSUE TITLE
GetKubernetesClusterConfigResponse is incorrect resulting in empty parsing

### ISSUE THREAD

**Issue by saffronjam** [apache/cloudstack-go#55]
```
type GetKubernetesClusterConfigResponse struct {
	Configdata string `json:"configdata"`
	Id         string `json:"id"`
	JobID      string `json:"jobid"`
	Jobstatus  int    `json:"jobstatus"`
	Name       string `json:"name"`
}
```

Should be:
```
type GetKubernetesClusterConfigResponse struct {
	ClusterConfig struct {
		Configdata string `json:"configdata"`
		Id         string `json:"id"`
		JobID      string `json:"jobid"`
		Jobstatus  int    `json:"jobstatus"`
		Name       string `json:"name"`
	} `json:"clusterconfig"`
}
``` 

Since the response is this (showing only the start since that is the only relevant part):
![image](https://user-images.githubusercontent.com/26722370/230050671-f4195177-1a6c-4f55-a5fb-83680bef4563.png)

CloudStack version: 4.18

**Comment by rohityadavcloud** [comment]
Thanks for reporting @saffronjam any PRs are welcome, I've also pinged @shwstppr to investigate and advise.

**Comment by saffronjam** [comment]
Hi! I have now provided a PR to fix this (that also added the missing test-data for the getKubernetesClusterConfig)

**Comment by mlsorensen** [comment]
For visibility, my comments from the base cloudstack issue:

I checked three different 'get' APIs via the golang client and they all either unmarshaled to an empty struct (since the response didn't match the struct), or threw an unmarshal error.

There's no formulaic way to determine what this base key should be, for getPathForVolume it is apipathforvolume. For getCloudIdentifier it is cloudidentifier, for getKubernetesClusterConfig  it is clusterconfig.
