### ISSUE TITLE
SDK question

### ISSUE THREAD

**Issue by CodeBleu** [apache/cloudstack-go#92]
@rohityadavcloud  I know this is prob not the correct/best place to post this, but it is somewhat related. There is currently an issue with Ansible and Cloudstack 4.19.  The issue is the main maintainer for the Cloudstack Python module no longer wants to maintain it.  Is this something that Shapeblue or Apache Cloudstack could take over to maintain?

https://github.com/exoscale/cs/issues/130#issuecomment-2495416724

**Comment by rohityadavcloud** [comment]
Hi @CodeBleu as you've followed yourself & Rene has notified us on the CloudStack mailing lists, the `cs` module is now maintained by him/ngine-io https://github.com/ngine-io/cs/issues/130#issuecomment-2504004096

We were busy last week due to [CCC/Madrid](https://www.cloudstackcollab.org), but if Rene wouldn't have offered I was going to suggest to accept `cs` as a CloudStack sub-project (like the go-sdk & few others).
